name: 'Hello World Docker Action'
on: [workflow_dispatch]
  
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Mr Wolf
        id: hello-action
        uses: mattisherwood/hello-world-docker-action@v1
        with:
          who-to-greet: 'Mr Wolf'
        
      - name: Whats the time Mr Wolf?
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when we said hello"
