name: 'Hello World Docker Action'
on: [workflow_dispatch]
  
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Whats the time Mr Wolf?
        uses: mattisherwood/hello-world-docker-action@v1
        with:
          who-to-greet: 'Mr Wolf'
