name: Deploy
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Demo Step
      run: echo "Pretend we built something..."
  notify:
    runs-on: ubuntu-latest
    if: always()
    needs: build
    steps:
    - name: Send a Notification (Dchourasia)
      uses: dchourasia/ms-teams-notification@1.0
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.TEAM_HOOK }}
#     - name: Send a Notification
#       id: notify
#       uses: thechetantalwar/teams-notify@v2
#       with:
#         teams_webhook_url: ${{ secrets.TEAM_HOOK }}
#         message: |
#           "# Github Action Build Number ${{ github.run_number }} Completed for ${{ github.repository }} Outcome is  ${{ needs.build.result }}."
