name: GitHub Actions Demo

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request_target:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This part is working on ${{ github.workflow.environment }}"

  Build:
    runs-on: ubuntu-latest
    environment: ${{ github.workflow.environment }}
    needs: test
    steps:
      - run: |
          echo "Event Trigger: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Respoitory: ${{ github.repository }}."

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
