name: GitHub Actions Demo

on:
  push:
    branches:
      main
    paths-ignore:
      .github/**
  pull_request_target:
    branches:
      main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is working"
