name: Reusable Workflow

on:
  workflow_call:
    inputs:
      who-to-greet:
        description: "Who to say hello to"
        type: string
        default: World
        required: true
    outputs:
      current-time:
        description: "What time did we say hello?"
        value: ${{ jobs.reusable-job.outputs.current-time }}
  
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello ${{ inputs.who-to-greet }}"
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
    outputs:
      current-time: ${{ steps.time.outputs.time }}
