name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: "@mattisherwood"
  
  use-output:
    needs: [call-workflow]
    runs-on: ubuntu-latest
    steps:
      - name: Write time to console
        run: echo "The workflow was run at ${{ needs.call-workflow.outputs.current-time }}"
